import Hero from './Hero';
import CustomButton from './CustomButton';
import Navbar from './Navbar';
import Footer from './Footer';
import AppTaskDay from './TaskDay/Taskday';
import AppCompany from './Company/Taskcompany';
import AppPersonal from './Personal/Taskpersonal';
import AppSider from './Sider/sider';
import AppHeader from './Header/Header';
export { Hero, CustomButton, Navbar, Footer, AppTaskDay, AppCompany, AppPersonal, AppSider, AppHeader };